%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 393.2731628417969
   fy: 393.2731628417969
   cx: 329.5204467773438
   cy: 245.5028839111328
